/**
 * Launch adapters. Conformance obligations (spec §2, §7): budgets enforced by
 * the caller, degradation visible, generated-file headers mandatory.
 *
 * Two emission styles:
 * - per-skill files (claude-code, cursor, copilot, cline, windsurf)
 * - marker-merged sections in a shared file (agentsmd → AGENTS.md, gemini → GEMINI.md)
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { estimateTokens, type LoadedSkill } from "./ksf.js";

export interface CompiledFile {
  path: string; // repo-relative
  content: string;
  /** marker-merged shared file: content is one skill's section, caller merges */
  merge?: boolean;
}

export interface AdapterOutput {
  files: CompiledFile[];
  /** Actionable problems (degradation, budget) — these fail `compile --strict`. */
  warnings: string[];
  /** Informational (the measured standing cost) — surfaced, but not a --strict failure. */
  notes?: string[];
}

export interface Adapter {
  id: string;
  /** Capabilities this target supports, matched against targets.requires. */
  capabilities: string[];
  /**
   * How the target loads a compiled skill:
   * - "lazy": kept out of context until invoked (Claude Code SKILL.md, Cursor agent-requested rules)
   * - "eager": always in the context window (AGENTS.md, GEMINI.md, Copilot applyTo, Cline/Windsurf rules)
   * An eager target cannot honor a skill authored to lazy-load; that costs its full body as standing context.
   */
  loading: "eager" | "lazy";
  detect(root: string): boolean;
  emit(skill: LoadedSkill, body: string, root: string): AdapterOutput;
  /**
   * Constraints this target enforces on a skill beyond what KSF validates, as
   * warnings. emit() folds these into its own; `explain` reads them directly, so
   * it can't answer "no degradation" about a skill the target silently discards.
   */
  lint?(skill: LoadedSkill): string[];
}

export const GENERATED_MARK = "generated by kitbash";

/** Quote a value as a double-quoted YAML scalar so descriptions with :, ", [, { etc. stay valid frontmatter. */
function yamlString(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function header(skill: LoadedSkill): string {
  const { name, version } = skill.manifest.skill;
  return `<!-- ${GENERATED_MARK} — do not edit; source: .kitbash/skills/${name} @ ${version} -->`;
}

function degradationWarnings(skill: LoadedSkill, adapter: Adapter): string[] {
  const missing = skill.manifest.targets.requires.filter((r) => !adapter.capabilities.includes(r));
  return missing.map(
    (cap) => `${skill.manifest.skill.name} → ${adapter.id}: target lacks "${cap}"; compiled instruction-only (degraded)`,
  );
}

function markers(name: string): { begin: string; end: string } {
  return { begin: `<!-- kitbash:begin ${name} -->`, end: `<!-- kitbash:end ${name} -->` };
}

/**
 * A skill authored to lazy-load (disclosure = "lazy") cannot lazy-load on an eager
 * target — the whole emitted file sits in context every session. This is measured
 * from the ACTUAL emitted files (not the pre-wrap body) so the number matches what
 * `preview` and the benchmark report for the same skill. It is a NOTE, not a warning:
 * it is the product's headline measurement, not a problem, so it never fails --strict.
 */
function eagerStandingNote(skill: LoadedSkill, adapter: Adapter, files: CompiledFile[]): string[] {
  if (adapter.loading !== "eager" || skill.manifest.context.disclosure !== "lazy") return [];
  const cost = files.reduce((sum, f) => sum + estimateTokens(f.content), 0);
  const { name } = skill.manifest.skill;
  return [
    `${name} → ${adapter.id}: ${adapter.id} is eager and cannot lazy-load, so this skill adds ~${cost} tokens standing every session (a lazy target pays 0; declared limit ${skill.manifest.context.standing})`,
  ];
}

/** Shared-file adapters (AGENTS.md, GEMINI.md): eager-loaded, marker-merged. */
function mergedFileAdapter(id: string, file: string, detect: (root: string) => boolean): Adapter {
  return {
    id,
    capabilities: [],
    loading: "eager",
    detect,
    emit(skill, body) {
      const { name } = skill.manifest.skill;
      const { begin, end } = markers(name);
      const section = `${begin}\n${header(skill)}\n\n## Skill: ${name}\n\n${body.trim()}\n${end}`;
      const files = [{ path: file, content: section, merge: true }];
      return { files, warnings: degradationWarnings(skill, this), notes: eagerStandingNote(skill, this, files) };
    },
  };
}

/** Simple per-skill file adapters that differ only in path, loading mode, and frontmatter. */
function fileAdapter(
  id: string,
  capabilities: string[],
  loading: "eager" | "lazy",
  detect: (root: string) => boolean,
  pathFor: (name: string, root: string) => string,
  frontmatter: (skill: LoadedSkill) => string,
): Adapter {
  return {
    id,
    capabilities,
    loading,
    detect,
    emit(skill, body, root) {
      const { name } = skill.manifest.skill;
      const content = `${frontmatter(skill)}${header(skill)}\n\n${body}`;
      const files = [{ path: pathFor(name, root), content }];
      return { files, warnings: degradationWarnings(skill, this), notes: eagerStandingNote(skill, this, files) };
    },
  };
}

const claudeCode: Adapter = {
  id: "claude-code",
  // Only capabilities emit() actually delivers. The adapter writes SKILL.md and
  // slash-command shims; it does not yet copy scripts/, install a hook, or wire a
  // subagent — so it must NOT claim those, or degradationWarnings computes an empty
  // missing-set and reports full support for output that references files it never
  // produced (the exact silent capability loss spec §2 forbids). Re-add a capability
  // only alongside the emit code that produces its primitive.
  capabilities: [],
  loading: "lazy",
  detect: (root) => existsSync(join(root, ".claude")),
  emit(skill, body) {
    const { name, description } = skill.manifest.skill;
    const files: CompiledFile[] = [
      {
        path: `.claude/skills/${name}/SKILL.md`,
        content: `---\nname: ${name}\ndescription: ${yamlString(description)}\n---\n${header(skill)}\n\n${body}`,
      },
    ];
    // Compile declared trigger commands into native slash commands (thin shims).
    for (const cmd of skill.manifest.triggers.commands) {
      const c = cmd.replace(/^\//, "");
      files.push({
        path: `.claude/commands/${c}.md`,
        content: `${header(skill)}\n\nLoad the "${name}" skill: read .claude/skills/${name}/SKILL.md and follow it exactly.\n\nArguments: $ARGUMENTS\n`,
      });
    }
    return { files, warnings: degradationWarnings(skill, this) };
  },
};

// Cursor rules with alwaysApply:false are agent-requested — lazy.
const cursor = fileAdapter(
  "cursor",
  [],
  "lazy",
  (root) => existsSync(join(root, ".cursor")),
  (name) => `.cursor/rules/${name}.mdc`,
  (skill) => `---\ndescription: ${yamlString(skill.manifest.skill.description)}\nalwaysApply: false\n---\n`,
);

/**
 * Copilot reads agentskills.io skills from `.github/skills/`, loading only the
 * frontmatter until the skill is needed. That is strictly cheaper than the
 * `applyTo: "**"` instructions file this used to emit, which applied to every
 * single request.
 */
const copilot = skillDirAdapter("copilot", ".github/skills", (root) => existsSync(join(root, ".github")));

/**
 * Agent Skills directories (agentskills.io): a folder per skill whose SKILL.md
 * carries `name` and `description` in frontmatter. Hosts inject only that
 * metadata at session start and load the body on demand, so these are lazy.
 *
 * `lint` reports constraints a specific host enforces on that frontmatter beyond
 * what KSF itself validates.
 */
function skillDirAdapter(
  id: string,
  dir: string,
  detect: (root: string) => boolean,
  lint?: (skill: LoadedSkill) => string[],
): Adapter {
  return {
    id,
    // Writes only SKILL.md — no scripts/ copied. Claim nothing emit() doesn't deliver.
    capabilities: [],
    loading: "lazy",
    detect,
    ...(lint ? { lint } : {}),
    emit(skill, body) {
      const { name, description } = skill.manifest.skill;
      return {
        files: [
          {
            path: `${dir}/${name}/SKILL.md`,
            content: `---\nname: ${name}\ndescription: ${yamlString(description)}\n---\n${header(skill)}\n\n${body}`,
          },
        ],
        warnings: [...degradationWarnings(skill, this), ...(lint?.(skill) ?? [])],
      };
    },
  };
}

/**
 * The vendor-neutral skills path, read by Codex (its only repo path), Cursor,
 * Copilot, Gemini CLI, Roo, Amp, OpenCode, Zed and Antigravity.
 *
 * Detection is deliberately narrow (`.agents/` or `.codex/`): agents that also
 * have a native path already get their own adapter, and emitting both would
 * duplicate the skill for no benefit.
 */
const agents = skillDirAdapter(
  "agents",
  ".agents/skills",
  (root) => existsSync(join(root, ".agents")) || existsSync(join(root, ".codex")),
);

/**
 * Zed's skill loader (`crates/agent_skills/agent_skills.rs`) is stricter than
 * KSF about frontmatter, and it fails *silently* — a skill that violates either
 * constraint is dropped with no diagnostic in the UI, which is the silent
 * capability loss spec §2 forbids. So the adapter says what Zed will not:
 *
 * - `name` must match ^[a-z0-9]+(-[a-z0-9]+)*$. KSF's NAME_RE is looser and
 *   permits a doubled or trailing hyphen (`tidy--commits`, `tidy-`), both of
 *   which Zed rejects. Its 64-character cap is unreachable from here: KSF names
 *   are capped at 41. `name` must also equal the containing directory name,
 *   which holds by construction — the directory IS the name.
 * - `description` must be non-empty and at most 1024 UTF-8 *bytes*, not
 *   characters. A manifested skill is bounded at 200 characters (600 bytes at
 *   worst), so only an unmanifested SKILL.md — whose frontmatter is copied
 *   through unvalidated — can breach either bound.
 *
 * No `disable-model-invocation` key is emitted. Zed accepts one, but KSF has no
 * field that means "never auto-invoke" (`triggers.auto` is a hint *for*
 * auto-invocation), so synthesizing a value would be guessing at the author's
 * intent and suppressing a skill they expect to fire.
 */
const ZED_NAME_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const ZED_DESCRIPTION_MAX_BYTES = 1024;
const SILENTLY_DROPPED = "Zed drops the skill at load with no diagnostic";

function zedConstraints(skill: LoadedSkill): string[] {
  const { name, description } = skill.manifest.skill;
  const out: string[] = [];
  if (!ZED_NAME_RE.test(name)) {
    out.push(`${name} → zed: name must match ${ZED_NAME_RE.source} — no leading, trailing or doubled hyphen; ${SILENTLY_DROPPED}`);
  }
  const bytes = new TextEncoder().encode(description).length;
  if (!description.trim()) {
    out.push(`${name} → zed: description is empty; ${SILENTLY_DROPPED}`);
  } else if (bytes > ZED_DESCRIPTION_MAX_BYTES) {
    out.push(
      `${name} → zed: description is ${bytes} bytes, over Zed's ${ZED_DESCRIPTION_MAX_BYTES}-byte limit (the limit is bytes, not characters); ${SILENTLY_DROPPED}`,
    );
  }
  return out;
}

/**
 * Zed reads the same vendor-neutral path, so this writes the byte-identical file
 * the `agents` adapter does — a repo with both `.zed/` and `.agents/` compiles
 * that skill once, not twice. What makes it its own target is detection and the
 * constraint check: `.zed/` is the only marker a Zed-only repo has, and without
 * this adapter such a repo compiles to nothing but the eager AGENTS.md floor —
 * paying a skill's whole body every session on an agent that can lazy-load it
 * for free.
 */
const zed = skillDirAdapter("zed", ".agents/skills", (root) => existsSync(join(root, ".zed")), zedConstraints);

/**
 * Cline reads Agent Skills, and has since it grew a skills loader
 * (`apps/vscode/src/core/storage/skill-directories.ts`): `.cline/skills`,
 * `.clinerules/skills`, `.claude/skills` and `.agents/skills` are all scanned.
 * Loading is progressive — name and description at startup, the body only when
 * `use_skill` fires.
 *
 * Until 0.13.0 this adapter wrote `.clinerules/<name>.md`, which is a *rule*:
 * always active, whole body in context, every session. That was wrong twice
 * over. It billed Cline ~539 standing tokens for a skill Cline was willing to
 * lazy-load for ~40, and in a repo that also had `.agents/` it emitted the same
 * body to both paths — so Cline loaded the skill twice, and the always-on copy
 * defeated the lazy one. A compiler whose entire claim is "cheapest loading
 * mode the target actually supports" was picking the most expensive mode
 * available and charging for it.
 *
 * Of the four scanned directories this emits to `.agents/skills`, the same
 * vendor-neutral path `agents` and `zed` use, rather than the `.cline/skills`
 * their docs nominate. Cline scans both equally, and sharing the path is what
 * makes the duplicate structurally impossible: one file serves Cline, Codex,
 * Cursor, Copilot and Zed at once, and a repo with several of their marker
 * directories still compiles that skill exactly once.
 */
const cline = skillDirAdapter(
  "cline",
  ".agents/skills",
  (root) => existsSync(join(root, ".clinerules")) || existsSync(join(root, ".cline")),
  clineConstraints,
);

/**
 * The mirror of the bug above: Cline loads every skill on demand, so a skill
 * authored `disclosure = "eager"` does not get the always-resident body its
 * author asked for. Compiling that silently would trade one conformance
 * violation (spec §2) for its reflection, so say it out loud.
 *
 * `.clinerules/<name>.md` would still deliver eager loading, and a
 * disclosure-aware two-path adapter is the obvious extension — but nobody has
 * asked for it, and a warning is the honest minimum in the meantime.
 */
function clineConstraints(skill: LoadedSkill): string[] {
  if (skill.manifest.context.disclosure !== "eager") return [];
  const { name } = skill.manifest.skill;
  return [
    `${name} → cline: authored disclosure = "eager", but Cline loads skills on demand — the body stays out of context until the model invokes it`,
  ];
}

/**
 * Windsurf became Devin Desktop on 2026-06-02; `.devin/rules/` is the preferred
 * path and `.windsurf/rules/` remains a supported fallback, so emit to whichever
 * the repo actually has. Directory rules carry an activation trigger in their
 * frontmatter — `model_decision` means the description is what sits in context
 * and the body loads only when the model judges it relevant, i.e. lazy.
 */
const windsurf = fileAdapter(
  "windsurf",
  [],
  "lazy",
  (root) => existsSync(join(root, ".devin")) || existsSync(join(root, ".windsurf")),
  (name, root) => (existsSync(join(root, ".devin")) ? `.devin/rules/${name}.md` : `.windsurf/rules/${name}.md`),
  (skill) => `---\ntrigger: model_decision\ndescription: ${yamlString(skill.manifest.skill.description)}\n---\n`,
);

/**
 * Gemini CLI discovers skills under `.gemini/skills/`, injecting only each
 * skill's name and description into the system prompt and pulling the body in
 * via its `activate_skill` tool. Previously this merged into GEMINI.md, which
 * Google's own docs describe as persistent workspace-wide background — the
 * whole body, every session. Old GEMINI.md sections are pruned on the next
 * compile; user content in that file is left alone.
 */
const gemini = skillDirAdapter(
  "gemini",
  ".gemini/skills",
  (root) => existsSync(join(root, "GEMINI.md")) || existsSync(join(root, ".gemini")),
);

// Aider reads CONVENTIONS.md (wired via .aider.conf.yml or --read); always in context — eager.
const aider = mergedFileAdapter(
  "aider",
  "CONVENTIONS.md",
  (root) => existsSync(join(root, "CONVENTIONS.md")) || existsSync(join(root, ".aider.conf.yml")),
);

/** The floor: everything that reads AGENTS.md (Codex and many others). */
const agentsmd = mergedFileAdapter("agentsmd", "AGENTS.md", () => true);

export const ADAPTERS: Adapter[] = [claudeCode, cursor, agents, zed, copilot, cline, windsurf, gemini, aider, agentsmd];

/** Replace or append a skill's marker-delimited section in shared-file content. */
export function mergeSection(existing: string, name: string, section: string): string {
  const { begin, end } = markers(name);
  const re = new RegExp(`${escapeRe(begin)}[\\s\\S]*?${escapeRe(end)}`);
  // Replacer function, not a replacement string: a skill body documenting `$$`
  // (Make), `$&` (sed), or `$'` would otherwise be reinterpreted as replacement
  // patterns — halving the `$$`, splicing the old section into itself, and
  // leaving doubled markers that break pruning on the next compile.
  if (re.test(existing)) return existing.replace(re, () => section);
  const sep = existing.trim().length ? `${existing.replace(/\s*$/, "")}\n\n` : "";
  return `${sep}${section}\n`;
}

/** Drop marker sections for skills no longer installed. */
export function pruneSections(content: string, installed: Set<string>): string {
  return content.replace(
    /<!-- kitbash:begin ([a-z0-9-]+) -->[\s\S]*?<!-- kitbash:end \1 -->\n?/g,
    (block, name: string) => (installed.has(name) ? block : ""),
  );
}

export function readFileIfExists(root: string, rel: string): string {
  const p = join(root, rel);
  return existsSync(p) ? readFileSync(p, "utf8") : "";
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
