/**
 * Launch adapters. Conformance obligations (spec §2, §7): budgets enforced by
 * the caller, degradation visible, generated-file headers mandatory.
 *
 * Two emission styles:
 * - per-skill files (claude-code, cursor, copilot, cline, windsurf)
 * - marker-merged sections in a shared file (agentsmd → AGENTS.md, gemini → GEMINI.md)
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { estimateTokens, type LoadedSkill } from "./ksf.js";

export interface CompiledFile {
  path: string; // repo-relative
  content: string;
  /** marker-merged shared file: content is one skill's section, caller merges */
  merge?: boolean;
}

export interface AdapterOutput {
  files: CompiledFile[];
  warnings: string[];
}

export interface Adapter {
  id: string;
  /** Capabilities this target supports, matched against targets.requires. */
  capabilities: string[];
  detect(root: string): boolean;
  emit(skill: LoadedSkill, body: string, root: string): AdapterOutput;
}

export const GENERATED_MARK = "generated by kitbash";

function header(skill: LoadedSkill): string {
  const { name, version } = skill.manifest.skill;
  return `<!-- ${GENERATED_MARK} — do not edit; source: .kitbash/skills/${name} @ ${version} -->`;
}

function degradationWarnings(skill: LoadedSkill, adapter: Adapter): string[] {
  const missing = skill.manifest.targets.requires.filter((r) => !adapter.capabilities.includes(r));
  return missing.map(
    (cap) => `${skill.manifest.skill.name} → ${adapter.id}: target lacks "${cap}"; compiled instruction-only (degraded)`,
  );
}

function markers(name: string): { begin: string; end: string } {
  return { begin: `<!-- kitbash:begin ${name} -->`, end: `<!-- kitbash:end ${name} -->` };
}

/** Shared-file adapters (AGENTS.md, GEMINI.md): eager-loaded, marker-merged. */
function mergedFileAdapter(id: string, file: string, note: string, detect: (root: string) => boolean): Adapter {
  return {
    id,
    capabilities: [],
    detect,
    emit(skill, body) {
      const { name } = skill.manifest.skill;
      const { begin, end } = markers(name);
      const section = `${begin}\n${header(skill)}\n\n## Skill: ${name}\n\n${body.trim()}\n${end}`;
      const warnings = degradationWarnings(skill, this);
      if (skill.manifest.context.disclosure === "lazy") {
        warnings.push(
          `${name} → ${id}: ${note} cannot lazy-load; §${name} costs ~${estimateTokens(body)} tokens standing (declared limit: ${skill.manifest.context.standing})`,
        );
      }
      return { files: [{ path: file, content: section, merge: true }], warnings };
    },
  };
}

/** Simple per-skill file adapters that differ only in path and frontmatter. */
function fileAdapter(
  id: string,
  capabilities: string[],
  detect: (root: string) => boolean,
  pathFor: (name: string) => string,
  frontmatter: (skill: LoadedSkill) => string,
): Adapter {
  return {
    id,
    capabilities,
    detect,
    emit(skill, body) {
      const { name } = skill.manifest.skill;
      const content = `${frontmatter(skill)}${header(skill)}\n\n${body}`;
      return { files: [{ path: pathFor(name), content }], warnings: degradationWarnings(skill, this) };
    },
  };
}

const claudeCode: Adapter = {
  id: "claude-code",
  capabilities: ["scripts", "hooks", "subagents"],
  detect: (root) => existsSync(join(root, ".claude")),
  emit(skill, body) {
    const { name, description } = skill.manifest.skill;
    const files: CompiledFile[] = [
      {
        path: `.claude/skills/${name}/SKILL.md`,
        content: `---\nname: ${name}\ndescription: ${description}\n---\n${header(skill)}\n\n${body}`,
      },
    ];
    // Compile declared trigger commands into native slash commands (thin shims).
    for (const cmd of skill.manifest.triggers.commands) {
      const c = cmd.replace(/^\//, "");
      files.push({
        path: `.claude/commands/${c}.md`,
        content: `${header(skill)}\n\nLoad the "${name}" skill: read .claude/skills/${name}/SKILL.md and follow it exactly.\n\nArguments: $ARGUMENTS\n`,
      });
    }
    return { files, warnings: degradationWarnings(skill, this) };
  },
};

const cursor = fileAdapter(
  "cursor",
  [],
  (root) => existsSync(join(root, ".cursor")),
  (name) => `.cursor/rules/${name}.mdc`,
  (skill) => `---\ndescription: ${skill.manifest.skill.description}\nalwaysApply: false\n---\n`,
);

const copilot = fileAdapter(
  "copilot",
  [],
  (root) => existsSync(join(root, ".github")),
  (name) => `.github/instructions/${name}.instructions.md`,
  () => `---\napplyTo: "**"\n---\n`,
);

const cline = fileAdapter(
  "cline",
  [],
  (root) => existsSync(join(root, ".clinerules")),
  (name) => `.clinerules/${name}.md`,
  () => "",
);

const windsurf = fileAdapter(
  "windsurf",
  [],
  (root) => existsSync(join(root, ".windsurf")),
  (name) => `.windsurf/rules/${name}.md`,
  () => "",
);

const gemini = mergedFileAdapter(
  "gemini",
  "GEMINI.md",
  "GEMINI.md",
  (root) => existsSync(join(root, "GEMINI.md")) || existsSync(join(root, ".gemini")),
);

/** The floor: everything that reads AGENTS.md (Codex and many others). */
const agentsmd = mergedFileAdapter("agentsmd", "AGENTS.md", "AGENTS.md", () => true);

export const ADAPTERS: Adapter[] = [claudeCode, cursor, copilot, cline, windsurf, gemini, agentsmd];

/** Replace or append a skill's marker-delimited section in shared-file content. */
export function mergeSection(existing: string, name: string, section: string): string {
  const { begin, end } = markers(name);
  const re = new RegExp(`${escapeRe(begin)}[\\s\\S]*?${escapeRe(end)}`);
  if (re.test(existing)) return existing.replace(re, section);
  const sep = existing.trim().length ? `${existing.replace(/\s*$/, "")}\n\n` : "";
  return `${sep}${section}\n`;
}

/** Drop marker sections for skills no longer installed. */
export function pruneSections(content: string, installed: Set<string>): string {
  return content.replace(
    /<!-- kitbash:begin ([a-z0-9-]+) -->[\s\S]*?<!-- kitbash:end \1 -->\n?/g,
    (block, name: string) => (installed.has(name) ? block : ""),
  );
}

export function readFileIfExists(root: string, rel: string): string {
  const p = join(root, rel);
  return existsSync(p) ? readFileSync(p, "utf8") : "";
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
