/** Working v0.1 commands: init, install, remove, list, compile, doctor. */

import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { ADAPTERS, AGENTS_MD, mergeAgentsSection, readAgentsMd, type CompiledFile } from "./adapters.js";
import { dropLock, integrityOf, readLock, upsertLock, LOCK_FILE } from "./lock.js";
import { estimateTokens, loadInstalledSkills, loadSkill, resolveBody, standingStub, NAME_RE, SKILLS_DIR, type LoadedSkill } from "./ksf.js";
import { parseToml } from "./toml.js";

const CONFIG = "kitbash.toml";
const GENERATED_MARK = "generated by kitbash";

const INIT_CONFIG = `# kitbash project configuration — https://github.com/singhharsh1708/kitbash
[project]
# Adapters to compile for. Omit to autodetect (.claude/, .cursor/, AGENTS.md floor).
# targets = ["claude-code", "cursor", "agentsmd"]
`;

export async function cmdInit(): Promise<number> {
  const root = process.cwd();
  if (existsSync(join(root, CONFIG))) {
    console.log(`${CONFIG} already exists — nothing to do`);
    return 0;
  }
  writeFileSync(join(root, CONFIG), INIT_CONFIG);
  mkdirSync(join(root, SKILLS_DIR), { recursive: true });
  console.log(`created ${CONFIG} and ${SKILLS_DIR}/`);
  console.log("next: kitbash install <gh:owner/repo | owner/repo | file:path>, then kitbash compile");
  return 0;
}

/** Accepts gh:owner/repo[/path][@ref], bare owner/repo[/path][@ref], file:path, or a local path. */
function normalizeSource(source: string, root: string): { kind: "gh" | "local"; value: string } {
  if (source.startsWith("gh:")) return { kind: "gh", value: source.slice(3) };
  if (source.startsWith("file:")) return { kind: "local", value: resolve(root, source.slice(5)) };
  const local = resolve(root, source);
  if (existsSync(local)) return { kind: "local", value: local };
  if (/^[\w.-]+\/[\w.-]+/.test(source)) return { kind: "gh", value: source };
  return { kind: "local", value: local }; // will fail with a clear "missing SKILL.md" error
}

export async function cmdInstall(args: string[]): Promise<number> {
  const source = args[0];
  if (!source) {
    console.error("usage: kitbash install <gh:owner/repo[/path][@ref] | owner/repo | file:path>");
    return 1;
  }
  const root = process.cwd();
  const normalized = normalizeSource(source, root);
  let cleanup: string | undefined;
  try {
    let dir: string;
    if (normalized.kind === "gh") {
      const m = normalized.value.match(/^([^/@]+)\/([^/@]+)(?:\/([^@]+))?(?:@(.+))?$/);
      if (!m) {
        console.error(`invalid source: ${source} (expected gh:owner/repo[/path][@ref])`);
        return 1;
      }
      const [, owner, repo, subpath, ref] = m;
      cleanup = mkdtempSync(join(tmpdir(), "kitbash-"));
      const url = `https://github.com/${owner}/${repo}.git`;
      const cloneArgs = ref ? ["clone", "--quiet", url, cleanup] : ["clone", "--quiet", "--depth", "1", url, cleanup];
      execFileSync("git", cloneArgs, { stdio: ["ignore", "ignore", "inherit"] });
      if (ref) execFileSync("git", ["-C", cleanup, "checkout", "--quiet", ref], { stdio: ["ignore", "ignore", "inherit"] });
      dir = subpath ? join(cleanup, subpath) : cleanup;
    } else {
      dir = normalized.value;
    }

    const skill = loadSkill(dir);
    const { name, version, description } = skill.manifest.skill;
    const dest = join(root, SKILLS_DIR, name);
    if (existsSync(dest)) {
      console.error(`${name} is already installed — kitbash remove ${name} first (update lands in v0.2)`);
      return 1;
    }
    mkdirSync(dirname(dest), { recursive: true });
    cpSync(dir, dest, { recursive: true });
    upsertLock(root, { name, version, source, integrity: integrityOf(dest) });

    console.log(`installed ${name}@${version} — ${description}`);
    console.log(`  budget ${skill.manifest.context.budget} tokens · standing ${skill.manifest.context.standing} · mode ${skill.manifest.targets.mode}`);
    if (skill.manifest.permissions.tools.length) console.log(`  permissions: ${skill.manifest.permissions.tools.join(", ")}`);
    if (skill.bare) console.log(`  ⚠ unmanifested (SKILL.md only) — defaults applied, no permissions or budget declared by the author`);
    console.log(`  pinned in ${LOCK_FILE}`);
    console.log("next: kitbash compile");
    return 0;
  } finally {
    if (cleanup) rmSync(cleanup, { recursive: true, force: true });
  }
}

export async function cmdRemove(args: string[]): Promise<number> {
  const name = args[0];
  if (!name || !NAME_RE.test(name)) {
    console.error("usage: kitbash remove <skill-name>");
    return 1;
  }
  const root = process.cwd();
  const dir = join(root, SKILLS_DIR, name);
  if (!existsSync(dir)) {
    console.error(`${name} is not installed`);
    return 1;
  }
  rmSync(dir, { recursive: true });
  dropLock(root, name);
  console.log(`removed ${name}`);
  console.log("next: kitbash compile (prunes this skill's generated outputs)");
  return 0;
}

export async function cmdList(): Promise<number> {
  const skills = loadInstalledSkills(process.cwd());
  if (!skills.length) {
    console.log("no skills installed — kitbash install <source>");
    return 0;
  }
  for (const s of skills) {
    const m = s.manifest;
    const bare = s.bare ? "  [unmanifested]" : "";
    console.log(`${m.skill.name}@${m.skill.version}  budget=${m.context.budget}  standing=${m.context.standing}  mode=${m.targets.mode}${bare}  — ${m.skill.description}`);
  }
  return 0;
}

export async function cmdDoctor(): Promise<number> {
  const root = process.cwd();
  console.log("detected targets:");
  for (const a of ADAPTERS) {
    const found = a.detect(root);
    const note = a.id === "agentsmd" ? " (floor: Codex, Gemini CLI, anything reading AGENTS.md)" : "";
    console.log(`  ${found ? "✓" : "✗"} ${a.id}${note}`);
  }

  const skills = loadInstalledSkills(root);
  const standing = skills.reduce((sum, s) => sum + estimateTokens(standingStub(s.body)), 0);
  const active = skills.reduce((sum, s) => sum + s.manifest.context.budget, 0);
  console.log(`installed skills: ${skills.length}`);
  console.log(`standing context cost: ~${standing} tokens (stubs); worst-case active: ${active} tokens (budgets)`);

  let drift = 0;
  for (const entry of readLock(root)) {
    const dir = join(root, SKILLS_DIR, entry.name);
    if (!existsSync(dir)) {
      console.log(`  ⚠ ${entry.name}: in ${LOCK_FILE} but not installed`);
      continue;
    }
    if (integrityOf(dir) !== entry.integrity) {
      console.error(`  ✗ ${entry.name}: integrity drift — installed files differ from ${LOCK_FILE}`);
      drift++;
    }
  }
  if (drift) {
    console.error(`${drift} skill(s) drifted from their lock — reinstall or investigate`);
    return 1;
  }
  console.log("lock integrity: ok");
  return 0;
}

function configuredAdapters(root: string): typeof ADAPTERS | string {
  const p = join(root, CONFIG);
  if (!existsSync(p)) return ADAPTERS.filter((a) => a.detect(root));
  const raw = parseToml(readFileSync(p, "utf8"));
  const project = raw["project"];
  const targets =
    project && typeof project === "object" && !Array.isArray(project) && Array.isArray(project["targets"])
      ? (project["targets"] as unknown[]).filter((t): t is string => typeof t === "string")
      : undefined;
  if (!targets) return ADAPTERS.filter((a) => a.detect(root));
  const unknown = targets.filter((t) => !ADAPTERS.some((a) => a.id === t));
  if (unknown.length) return `unknown target(s) in ${CONFIG}: ${unknown.join(", ")} (known: ${ADAPTERS.map((a) => a.id).join(", ")})`;
  return ADAPTERS.filter((a) => targets.includes(a.id));
}

export async function cmdCompile(args: string[]): Promise<number> {
  const strict = args.includes("--strict");
  const root = process.cwd();
  const skills = loadInstalledSkills(root);
  if (!skills.length) {
    console.error("no skills installed — kitbash install <source> first");
    return 1;
  }

  const adaptersOrError = configuredAdapters(root);
  if (typeof adaptersOrError === "string") {
    console.error(adaptersOrError);
    return 1;
  }
  const adapters = adaptersOrError;
  const installedNames = new Set(skills.map((s) => s.manifest.skill.name));

  const files = new Map<string, string>();
  const warnings: string[] = [];
  let agentsContent = pruneAgentsSections(readAgentsMd(root), installedNames);

  for (const skill of skills) {
    const body = resolveBody(skill);
    const { name } = skill.manifest.skill;
    if (skill.bare) warnings.push(`${name}: unmanifested (SKILL.md only) — defaults applied, no permissions declared`);
    const over = budgetViolations(skill, body);
    if (over.length && !skill.bare) {
      for (const v of over) console.error(`✗ ${v}`);
      return 1;
    }
    warnings.push(...over); // bare skills: report, don't fail — the author never declared these limits

    for (const adapter of adapters) {
      const out = adapter.emit(skill, body, root);
      warnings.push(...out.warnings);
      for (const f of out.files) {
        if (f.path === AGENTS_MD) {
          agentsContent = mergeAgentsSection(agentsContent, name, f.content);
          files.set(AGENTS_MD, agentsContent);
        } else {
          files.set(f.path, f.content);
        }
      }
    }
  }

  const written: CompiledFile[] = [...files.entries()].map(([path, content]) => ({ path, content }));
  for (const f of written) {
    const abs = join(root, f.path);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, f.content.endsWith("\n") ? f.content : `${f.content}\n`);
    console.log(`→ ${f.path}`);
  }
  for (const pruned of pruneStaleOutputs(root, installedNames)) console.log(`✂ ${pruned}`);
  for (const w of warnings) console.log(`⚠ ${w}`);
  console.log(`compiled ${skills.length} skill(s) for ${adapters.length} agent target(s)`);
  if (strict && warnings.length) {
    console.error(`--strict: failing on ${warnings.length} warning(s)`);
    return 1;
  }
  return 0;
}

function budgetViolations(skill: LoadedSkill, body: string): string[] {
  const { name } = skill.manifest.skill;
  const { budget, standing } = skill.manifest.context;
  const out: string[] = [];
  const bodyTokens = estimateTokens(body);
  if (bodyTokens > budget) out.push(`${name}: compiled body is ~${bodyTokens} tokens, over its budget of ${budget}`);
  const stubTokens = estimateTokens(standingStub(body));
  if (stubTokens > standing) out.push(`${name}: standing stub is ~${stubTokens} tokens, over its standing limit of ${standing}`);
  return out;
}

/** Drop AGENTS.md sections for skills that are no longer installed. */
function pruneAgentsSections(content: string, installed: Set<string>): string {
  return content.replace(
    /<!-- kitbash:begin ([a-z0-9-]+) -->[\s\S]*?<!-- kitbash:end \1 -->\n?/g,
    (block, name: string) => (installed.has(name) ? block : ""),
  );
}

/** Delete generated per-skill outputs for skills that are no longer installed. */
function pruneStaleOutputs(root: string, installed: Set<string>): string[] {
  const pruned: string[] = [];

  const claudeBase = join(root, ".claude/skills");
  if (existsSync(claudeBase)) {
    for (const e of readdirSync(claudeBase, { withFileTypes: true })) {
      if (!e.isDirectory() || installed.has(e.name)) continue;
      const skillMd = join(claudeBase, e.name, "SKILL.md");
      if (existsSync(skillMd) && readFileSync(skillMd, "utf8").includes(GENERATED_MARK)) {
        rmSync(join(claudeBase, e.name), { recursive: true });
        pruned.push(`removed .claude/skills/${e.name}/ (stale)`);
      }
    }
  }

  const cursorBase = join(root, ".cursor/rules");
  if (existsSync(cursorBase)) {
    for (const e of readdirSync(cursorBase, { withFileTypes: true })) {
      if (!e.isFile() || !e.name.endsWith(".mdc")) continue;
      const name = basename(e.name, ".mdc");
      if (installed.has(name)) continue;
      const p = join(cursorBase, e.name);
      if (readFileSync(p, "utf8").includes(GENERATED_MARK)) {
        rmSync(p);
        pruned.push(`removed .cursor/rules/${e.name} (stale)`);
      }
    }
  }

  return pruned;
}
