/**
 * kitbash.lock — content-hash pins for installed skills.
 * Hashes are the truth; versions are human convenience (spec §8).
 */

import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, readlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseToml, type TomlTable } from "./toml.js";

export const LOCK_FILE = "kitbash.lock";

export interface LockEntry {
  name: string;
  version: string;
  source: string;
  integrity: string;
}

export function readLock(root: string): LockEntry[] {
  const p = join(root, LOCK_FILE);
  if (!existsSync(p)) return [];
  const raw = parseToml(readFileSync(p, "utf8"));
  const arr = raw["skill"];
  if (!Array.isArray(arr)) return [];
  return arr
    .filter((e): e is TomlTable => typeof e === "object" && !Array.isArray(e))
    .map((e) => ({
      name: String(e["name"] ?? ""),
      version: String(e["version"] ?? ""),
      source: String(e["source"] ?? ""),
      integrity: String(e["integrity"] ?? ""),
    }))
    .filter((e) => e.name);
}

export function writeLock(root: string, entries: LockEntry[]): void {
  const sorted = [...entries].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  const blocks = sorted.map(
    (e) =>
      `[[skill]]\nname = ${JSON.stringify(e.name)}\nversion = ${JSON.stringify(e.version)}\nsource = ${JSON.stringify(e.source)}\nintegrity = ${JSON.stringify(e.integrity)}`,
  );
  writeFileSync(join(root, LOCK_FILE), `# generated by kitbash — do not edit\n\n${blocks.join("\n\n")}\n`);
}

export function upsertLock(root: string, entry: LockEntry): void {
  writeLock(root, [...readLock(root).filter((e) => e.name !== entry.name), entry]);
}

export function dropLock(root: string, name: string): void {
  writeLock(root, readLock(root).filter((e) => e.name !== name));
}

/**
 * Deterministic hash over a skill directory: sorted relative paths + contents.
 * Cross-platform stable: paths are NFC-normalized (macOS returns NFD), sorted by
 * binary code-unit order (locale-independent), and text content is CRLF→LF
 * normalized so a Windows checkout with core.autocrlf doesn't read as drift.
 */
export function integrityOf(dir: string): string {
  const hash = createHash("sha256");
  for (const { path: rel, symlink } of walk(dir, "")) {
    hash.update(rel); // NFC-normalized in walk()
    hash.update("\0");
    if (symlink) {
      // Hash the link target itself, without following it — cpSync copies symlinks,
      // so repointing one (e.g. an adapter-referenced script) would otherwise be
      // invisible drift, and readFileSync would dereference and throw on a dangling link.
      hash.update("\x01symlink\x01");
      hash.update(readlinkSync(join(dir, rel)));
    } else {
      hash.update(hashableContent(readFileSync(join(dir, rel))));
    }
    hash.update("\0");
  }
  return `sha256-${hash.digest("hex")}`;
}

/** Normalize line endings for text files (leave binary untouched) so CRLF vs LF isn't false drift. */
function hashableContent(buf: Buffer): Buffer {
  if (buf.includes(0)) return buf; // NUL byte ⇒ treat as binary, hash verbatim
  return Buffer.from(buf.toString("utf8").replace(/\r\n/g, "\n"), "utf8");
}

/**
 * Every entry under a directory, NFC-normalized and binary-sorted. Exported so the
 * install safety lints can scan the whole skill, not just SKILL.md. Symlinks are
 * reported (symlink: true) but not followed.
 */
export function walk(base: string, rel: string): { path: string; symlink: boolean }[] {
  const out: { path: string; symlink: boolean }[] = [];
  const entries = readdirSync(join(base, rel), { withFileTypes: true })
    .map((e) => ({ e, name: e.name.normalize("NFC") }))
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  for (const { e, name } of entries) {
    const r = rel ? `${rel}/${name}` : name;
    if (e.isSymbolicLink()) out.push({ path: r, symlink: true });
    else if (e.isDirectory()) out.push(...walk(base, r));
    else if (e.isFile()) out.push({ path: r, symlink: false });
  }
  return out;
}
