/**
 * kitbash.lock — content-hash pins for installed skills.
 * Hashes are the truth; versions are human convenience (spec §8).
 */

import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseToml, type TomlTable } from "./toml.js";

export const LOCK_FILE = "kitbash.lock";

export interface LockEntry {
  name: string;
  version: string;
  source: string;
  integrity: string;
}

export function readLock(root: string): LockEntry[] {
  const p = join(root, LOCK_FILE);
  if (!existsSync(p)) return [];
  const raw = parseToml(readFileSync(p, "utf8"));
  const arr = raw["skill"];
  if (!Array.isArray(arr)) return [];
  return arr
    .filter((e): e is TomlTable => typeof e === "object" && !Array.isArray(e))
    .map((e) => ({
      name: String(e["name"] ?? ""),
      version: String(e["version"] ?? ""),
      source: String(e["source"] ?? ""),
      integrity: String(e["integrity"] ?? ""),
    }))
    .filter((e) => e.name);
}

export function writeLock(root: string, entries: LockEntry[]): void {
  const sorted = [...entries].sort((a, b) => a.name.localeCompare(b.name));
  const blocks = sorted.map(
    (e) =>
      `[[skill]]\nname = ${JSON.stringify(e.name)}\nversion = ${JSON.stringify(e.version)}\nsource = ${JSON.stringify(e.source)}\nintegrity = ${JSON.stringify(e.integrity)}`,
  );
  writeFileSync(join(root, LOCK_FILE), `# generated by kitbash — do not edit\n\n${blocks.join("\n\n")}\n`);
}

export function upsertLock(root: string, entry: LockEntry): void {
  writeLock(root, [...readLock(root).filter((e) => e.name !== entry.name), entry]);
}

export function dropLock(root: string, name: string): void {
  writeLock(root, readLock(root).filter((e) => e.name !== name));
}

/** Deterministic hash over a skill directory: sorted relative paths + contents. */
export function integrityOf(dir: string): string {
  const hash = createHash("sha256");
  for (const rel of walk(dir, "")) {
    hash.update(rel);
    hash.update("\0");
    hash.update(readFileSync(join(dir, rel)));
    hash.update("\0");
  }
  return `sha256-${hash.digest("hex")}`;
}

function walk(base: string, rel: string): string[] {
  const out: string[] = [];
  const entries = readdirSync(join(base, rel), { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name));
  for (const e of entries) {
    const r = rel ? `${rel}/${e.name}` : e.name;
    if (e.isDirectory()) out.push(...walk(base, r));
    else if (e.isFile()) out.push(r);
  }
  return out;
}
