/**
 * End-to-end test of the v0.1 thin slice: init → install file: → compile
 * → verify adapter outputs, budget report, idempotent AGENTS.md merge.
 */
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");
const cli = join(here, "../dist/index.js");
const fixture = join(repoRoot, "examples/skills/prereview");

let failures = 0;
function check(name, cond, detail = "") {
  if (cond) {
    console.log(`  ok  ${name}`);
  } else {
    failures++;
    console.error(`FAIL  ${name}${detail ? ` — ${detail}` : ""}`);
  }
}

function run(args, cwd) {
  const r = spawnSync("node", [cli, ...args], { cwd, encoding: "utf8" });
  return { status: r.status, out: `${r.stdout}${r.stderr}` };
}

const tmp = mkdtempSync(join(tmpdir(), "kitbash-e2e-"));
try {
  mkdirSync(join(tmp, ".claude"));
  mkdirSync(join(tmp, ".cursor"));

  const init = run(["init"], tmp);
  check("init exits 0", init.status === 0, init.out);
  check("init writes kitbash.toml", existsSync(join(tmp, "kitbash.toml")));

  const install = run(["install", `file:${fixture}`], tmp);
  check("install exits 0", install.status === 0, install.out);
  check("install reports budget", install.out.includes("budget 1500 tokens"), install.out);

  const dup = run(["install", `file:${fixture}`], tmp);
  check("duplicate install rejected", dup.status === 1, dup.out);

  const list = run(["list"], tmp);
  check("list shows skill", list.out.includes("prereview@0.1.0"), list.out);

  const compile = run(["compile"], tmp);
  check("compile exits 0", compile.status === 0, compile.out);
  check("compile summary", compile.out.includes("compiled 1 skill(s) for 3 agent target(s)"), compile.out);

  const claude = join(tmp, ".claude/skills/prereview/SKILL.md");
  const cursor = join(tmp, ".cursor/rules/prereview.mdc");
  const agents = join(tmp, "AGENTS.md");
  check("claude-code output exists", existsSync(claude));
  check("cursor output exists", existsSync(cursor));
  check("agentsmd output exists", existsSync(agents));

  const claudeContent = readFileSync(claude, "utf8");
  check("claude output has frontmatter name", claudeContent.includes("name: prereview"));
  check("claude output has generated header", claudeContent.includes("generated by kitbash"));
  check("template vars resolved", claudeContent.includes(".kitbash/artifacts/plan.json") && !claudeContent.includes("{{"));

  const agentsContent = readFileSync(agents, "utf8");
  check("agentsmd markers present", agentsContent.includes("<!-- kitbash:begin prereview -->") && agentsContent.includes("<!-- kitbash:end prereview -->"));
  check("eager-load warning surfaced", compile.out.includes("cannot lazy-load"), compile.out);

  const recompile = run(["compile"], tmp);
  const markerCount = (readFileSync(agents, "utf8").match(/kitbash:begin prereview/g) ?? []).length;
  check("recompile idempotent (single AGENTS.md section)", recompile.status === 0 && markerCount === 1, `markers=${markerCount}`);

  const strict = run(["compile", "--strict"], tmp);
  check("--strict fails on warnings", strict.status === 1, strict.out);

  const doctor = run(["doctor"], tmp);
  check("doctor exits 0", doctor.status === 0, doctor.out);
  check("doctor reports standing cost", doctor.out.includes("standing context cost"), doctor.out);

  const remove = run(["remove", "prereview"], tmp);
  check("remove exits 0", remove.status === 0, remove.out);
  check("skill dir gone", !existsSync(join(tmp, ".kitbash/skills/prereview")));
} finally {
  rmSync(tmp, { recursive: true, force: true });
}

if (failures) {
  console.error(`\n${failures} test(s) failed`);
  process.exit(1);
}
console.log("\nall tests passed");
